In [1]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

import yaml
import webbrowser

In [2]:
config_file = "../config.yaml"
with open(config_file, 'r') as f:
    config = yaml.safe_load(f)

In [3]:
file_full = "../data/data.parquet"
file_min = "../data/min_data_format.parquet"

In [4]:
df_full = pd.read_parquet(file_full)
df_min = pd.read_parquet(file_min)

check differences between data (df_full) and min_data_format (df_min) and decide with which to continue

In [5]:
list(df_full.columns)

['id_hash',
 'id_url',
 'url',
 'title',
 'description',
 'more_info',
 'legal_basis',
 'contact_info_institution',
 'contact_info_street',
 'contact_info_city',
 'contact_info_fax',
 'contact_info_phone',
 'contact_info_email',
 'contact_info_website',
 'funding_type',
 'funding_area',
 'funding_location',
 'eligible_applicants',
 'funding_body',
 'further_links',
 'checksum',
 'license_info',
 'previous_update_dates',
 'last_updated',
 'on_website_from',
 'deleted']

In [6]:
list(df_min.columns)

['id_hash',
 'deleted',
 'on_website_from',
 'url',
 'title',
 'description',
 'more_info',
 'legal_basis',
 'funding_type',
 'funding_area',
 'funding_location',
 'eligible_applicants',
 'funding_body']

In [7]:
[c for c in list(df_full.columns) if c not in list(df_min.columns)]

['id_url',
 'contact_info_institution',
 'contact_info_street',
 'contact_info_city',
 'contact_info_fax',
 'contact_info_phone',
 'contact_info_email',
 'contact_info_website',
 'further_links',
 'checksum',
 'license_info',
 'previous_update_dates',
 'last_updated']

df_min seems sufficient for analysis

In [8]:
df_min

,id_hash,deleted,on_website_from,url,title,description,more_info,legal_basis,funding_type,funding_area,funding_location,eligible_applicants,funding_body
0,8997afac2cd4a1c4a032f5a5589e381e,False,2025-10-27 02:02:12.484091,https://www.foerderdatenbank.de/FDB/Content/DE...,Aktionsprogramm „Hilfen in Wohnungsnotfällen“,### Kurztext\n\nWenn Sie Maßnahmen zur Verhind...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Aktionsprogramm „Hilfen in...,Zuschuss,Gesundheit & Soziales,Nordrhein-Westfalen,"Kommune, Verband/Vereinigung","Ministerium für Arbeit, Gesundheit und Soziale..."
1,b5d0bc46cd945fbba2132d73dfe33c98,False,2025-10-17 02:02:14.333933,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Projekten zum Thema „Zukunftstec...,##### Rechtsgrundlage\n\nRichtlinie zur Förder...,None,None,Zuschuss,Forschung & Innovation (themenspezifisch),bundesweit,"Forschungseinrichtung, Hochschule, Unternehmen...","Bundesministerium für Forschung, Technologie u..."
2,8be11300265934d4afcb8680f1ac2eff,False,2025-10-25 02:02:15.087948,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Maßnahmen des Natürlichen Klimas...,##### Rechtsgrundlage\n\nRichtlinie zur Förder...,None,None,"Darlehen, Zuschuss",Umwelt- & Naturschutz,bundesweit,Unternehmen,"Bundesministerium für Umwelt, Klimaschutz, Nat..."
3,29b4379eb1004eca5fa67b2b053da017,False,2025-10-17 02:02:14.333933,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Forschungsvorhaben von Hochschul...,##### Rechtsgrundlage\n\nRichtlinie zur Förder...,None,None,Zuschuss,Forschung & Innovation (themenoffen),bundesweit,Hochschule,"Bundesministerium für Forschung, Technologie u..."
4,d6482c35f239991eb467b7fba412b2b8,False,2025-10-25 02:02:15.087948,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Projekten kommunaler und sonstig...,### Kurztext\n\nWenn Sie als nicht staatliches...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Förderung von Projekten ko...,Zuschuss,"Kultur, Medien & Sport",Rheinland-Pfalz,"Kommune, Verband/Vereinigung",
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2567,58c44f8d4e0a3a5a187fb46bba2bee5c,True,2025-06-27 02:00:49.757979,https://www.foerderdatenbank.de/FDB/Content/DE...,Dekarbonisierungsbonus Thüringen,### Kurztext\n\nWenn Sie in Ihrem Unternehmen ...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie zum Förderprogr...,Zuschuss,Energieeffizienz & Erneuerbare Energien,Thüringen,Unternehmen,"Thüringer Ministerium für Wirtschaft, Wissensc..."
2568,5c510714a36b1d412c2dbcae140b0210,True,2025-06-19 14:40:33.793034,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung der Flurbereinigung (FlurbFördRichtl...,### Kurztext\n\nWenn Sie an Maßnahmen zur Flur...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie des Ministerium...,Zuschuss,Landwirtschaft & Ländliche Entwicklung,Brandenburg,"Unternehmen, Privatperson, Verband/Vereinigung","Ministerium für Landwirtschaft, Umwelt und Kli..."
2569,d1045324bdb05fb1150c99f5a4cee386,True,2025-06-19 14:40:33.793034,https://www.foerderdatenbank.de/FDB/Content/DE...,Wohnraumförderungsprogramm – Sonderprogramm zu...,### Kurztext\n\nWenn Sie in Gebieten mit Wohnu...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Verwaltungsvorschrift des ...,Darlehen,Wohnungsbau & Modernisierung,Saarland,"Privatperson, Unternehmen, Verband/Vereinigung","Ministerium für Inneres, Bauen und Sport"
2570,472c86ae2d94c7452a356f3b98ea3c94,True,2025-06-19 14:40:33.793034,https://www.foerderdatenbank.de/FDB/Content/DE...,Wohnraumförderung – Modernisierung von Mietwoh...,**Wohnraumförderung – Modernisierung von Mietw...,None,None,"Darlehen, Zuschuss",Wohnungsbau & Modernisierung,Niedersachsen,"Privatperson, Öffentliche Einrichtung, Kommune...","Niedersächsisches Ministerium für Wirtschaft, ..."
2571,bbe924581ed4c29e79e731884aedf0c4,True,2025-06-19 14:40:33.793034,https://www.foerderdatenbank.de/FDB/Content/DE...,Schaffung von barrierefreiem Mietwohnraum,"### Kurztext\n\nWenn Sie Baumaßnahmen planen, ...",### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Verwaltungsvorschrift des ...,Zuschuss,Wohnungsbau & Modernisierung,Saarland,"Kommune, Öffentliche Einrichtung, Privatperson...","Ministerium für Inneres, Bauen und Sport"

# Questions for EDA

## Which programms aim at funding democracy?

In [9]:
df_min_demo = df_min.loc[df_min["description"].str.lower().str.contains("demokrati")]
df_min_demo

,id_hash,deleted,on_website_from,url,title,description,more_info,legal_basis,funding_type,funding_area,funding_location,eligible_applicants,funding_body
40,94c9ca4bbdcfb607618ddd64d80078c7,False,2025-09-07 02:05:53.646508,https://www.foerderdatenbank.de/FDB/Content/DE...,Zuwendungen für Projekte in der Weiterbildung,### Kurztext\n\nWenn Sie als Bildungsträger in...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie über die Gewähr...,Zuschuss,"Aus- & Weiterbildung, Frauenförderung",Rheinland-Pfalz,Bildungseinrichtung,"Ministerium für Arbeit, Soziales, Transformati..."
286,73ac2b6906d2587a1c5cafe5a1feea75,False,2025-10-31 02:02:34.906189,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderrichtlinie EFRE-Programm Stadtteilzentre...,### Kurztext\n\nWenn Sie Maßnahmen zur nachhal...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Förderrichtlinie „Programm...,Zuschuss,"Gesundheit & Soziales, Infrastruktur",Berlin,"Öffentliche Einrichtung, Verband/Vereinigung","Senatsverwaltung für Arbeit, Soziales, Gleichs..."
486,5b257a66bca8392e3945e8f63b1af6d0,False,2025-09-27 02:02:56.017839,https://www.foerderdatenbank.de/FDB/Content/DE...,Opfer- und Präventionshilfe,### Kurztext\n\nWenn Sie Maßnahmen in der frei...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Verwaltungsvorschrift des ...,Zuschuss,Infrastruktur,Sachsen,Verband/Vereinigung,Sächsisches Staatsministerium der Justiz und f...
507,fb40aaa441a686037d132bded1cb6c96,False,2025-09-25 02:01:36.214979,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung der Weiterentwicklung der Kinder- un...,"### Kurztext\n\nWenn Sie Maßnahmen planen, die...",### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie des Sächsischen...,Zuschuss,Gesundheit & Soziales,Sachsen,"Kommune, Verband/Vereinigung",Sächsisches Staatsministerium für Soziales und...
563,90b8c83dea493c4b60366d898d231366,False,2025-10-29 02:02:24.873869,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Maßnahmen zur Stärkung von Demok...,### Kurztext\n\nWenn Sie demokratisches Bewuss...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie für die Gewähru...,Zuschuss,"Kultur, Medien & Sport",Mecklenburg-Vorpommern,"Bildungseinrichtung, Kommune, Öffentliche Einr...","Ministerium für Wissenschaft, Kultur, Bundes- ..."
570,ee09f19050b2f909c05887cdf5ee820d,False,2025-10-29 02:02:24.873869,https://www.foerderdatenbank.de/FDB/Content/DE...,Projekte zur Bildung für nachhaltige Entwicklu...,### Kurztext\n\nWenn Sie Projekte im Bereich d...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie für die Gewähru...,Zuschuss,"Gesundheit & Soziales, Kultur, Medien & Sport",Mecklenburg-Vorpommern,"Kommune, Privatperson, Öffentliche Einrichtung...","Ministerium für Wissenschaft, Kultur, Bundes- ..."
572,e6def579f2f13e147df1921f5ab9ab57,False,2025-10-29 02:02:24.873869,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung im Rahmen der Förderrichtlinie „Akti...,### Kurztext\n\nWenn Sie in Hamburg Maßnahmen ...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Förderrichtlinie „Aktiv fü...,Zuschuss,"Kultur, Medien & Sport",Hamburg,"Bildungseinrichtung, Privatperson, Verband/Ver...","Behörde für Arbeit, Gesundheit, Soziales, Fami..."
793,67e0acac0b9837a91570ea83ea5b06c3,False,2025-10-19 02:01:44.187021,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung modellhafter und innovativer Projekt...,### Kurztext\n\nWenn Sie innovative Projektide...,### Fristen\n\nDie Frist zur Einreichung von P...,### Richtlinie\n\n**Bekanntmachung Nr. 01/2024...,Zuschuss,"Landwirtschaft & Ländliche Entwicklung, Digita...",bundesweit,Kommune,"Bundesministerium für Landwirtschaft, Ernährun..."
813,9004f112d3f865010a2fa6ae3d8ac69d,False,2025-10-31 02:02:34.906189,https://www.foerderdatenbank.de/FDB/Content/DE...,Bundesprogramm „Zusammenhalt durch Teilhabe“,### Kurztext\n\nWenn Sie als Verein oder Verba...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\nFörderrichtlinie des Bundesp...,Zuschuss,"Kultur, Medien & Sport",bundesweit,"Verband/Vereinigung, Bildungseinrichtung",Bundesministerium des Innern (BMI)
849,86d63cd63ca12e0ffd602839880e0f1d,False,2025-10-19 02:01:44.187021,https://www.foerderdatenbank.de/FDB/Content/DE...,"Förderung von Demokratie, Toleranz und Weltoff...",### Kurztext\n\nWenn Sie Maßnahmen durchführen...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie „Förderung von ...,Zuschuss,"Kultur, Medien & Sport",Thüringen,"Verband/Vereinigung, Öffentliche Einrichtung, ...","Thüringer Ministerium für Bildung, Jugend und ..."
970,7c6945a6ad13bab32155f20ba7e1d64b,False,2025-10-29 02:02:24.873869,https://www.foerderdatenbank.de/FDB/Content/DE...,Zuwendungen für Maßnahmen zur Stärkung von Vie...,##### Rechtsgrundlage\n\nFörderrichtlinie zur ...,None,None,Zuschuss,Gesundheit & Soziales,bundesweit,"Verband/Vereinigung, Öffentliche Einrichtung, ...","Bundesministerium für Bildung, Familie, Senior..."
977,87074b488a5ae7adec2374630ffac757,False,2025-10-31 02:02:34.906189,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Maßnahmen der politischen Bildun...,### Kurztext\n\nWenn Sie politische Bildungsan...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\nRichtlinie des Ministeriums ...,Zuschuss,"Aus- & Weiterbildung, Kultur, Medien & Sport",Brandenburg,"Verband/Vereinigung, Bildungseinrichtung","Ministerium für Bildung, Jugend und Sport des ..."
1047,a2e43b78f39bd894e22c12049685c8b5,False,2025-10-31 02:02:34.906189,https://www.foerderdatenbank.de/FDB/Content/DE...,Justiz (2021–2027),### Kurztext\n\nDas Justiz-Programm bildet die...,### rechtliche Voraussetzungen\n\nDas Programm...,### Richtlinie\n\n**Verordnung (EU) 2021/693 d...,Zuschuss,Aus- & Weiterbildung,bundesweit,"Bildungseinrichtung, Öffentliche Einrichtung, ...",Europäische Kommission
1049,7b228e2288ba3580d0aaac6df450b7f2,False,2025-10-31 02:02:34.906189,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderungen im Rahmen des Programms „Bürgerinn...,### Kurztext\n\nWenn Sie sich für Themen in de...,### Fristen\n\nDie Fristen für alle offenen Fö...,### Richtlinie\n\n**Verordnung (EU) 2021/692 d...,Zuschuss,"Aus- & Weiterbildung, Frauenförderung, Gesundh...",bundesweit,"Bildungseinrichtung, Kommune, Öffentliche Einr...",Europäische Kommission
1070,892750f7bab363532b99225c7886cd11,False,2025-09-11 02:01:35.790153,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Forschungsvorhaben „Plattform Pr...,### Kurztext\n\nWenn Sie die Herausforderungen...,### Fristen\n\nProjektskizzen können jederzeit...,### Richtlinie\n\nRichtlinie zur Förderung von...,Zuschuss,"Forschung & Innovation (themenspezifisch), Dig...",bundesweit,"Forschungseinrichtung, Hochschule, Unternehmen...","Bundesministerium für Forschung, Technologie u..."
1078,6ffabc0b58132026bac43c0c2a98c7c1,False,2025-10-01 02:03:02.880595,https://www.foerderdatenbank.de/FDB/Content/DE...,Maßnahmen im Rahmen des Landesprogramms für De...,### Kurztext\n\nWenn Sie als Verein oder Verba...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie über die Gewähr...,Zuschuss,"Kultur, Medien & Sport",Sachsen-Anhalt,"Öffentliche Einrichtung, Verband/Vereinigung","Ministerium für Arbeit, Soziales, Gesundheit u..."
1147,dbe42eeb6d3ea7a6cdcc0042fbd702ce,False,2025-10-29 02:02:24.873869,https://www.foerderdatenbank.de/FDB/Content/DE...,Weltoffenes Sachsen für Demokratie und Toleran...,"### Kurztext\n\nWenn Sie Projekte planen, mit ...",### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie des Sächsischen...,Zuschuss,"Gesundheit & Soziales, Kultur, Medien & Sport",Sachsen,"Bildungseinrichtung, Kommune, Hochschule, Verb...",Sächsisches Staatsministerium für Soziales und...
1442,8ffe020806da74d919f01aacec7e81f9,False,2025-10-01 02:03:02.880595,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung des Freiwilligen Sozialen Jahres (FSJ),### Kurztext\n\nWenn Sie in Mecklenburg-Vorpom...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie zur Förderung d...,Zuschuss,Gesundheit & Soziales,Mecklenburg-Vorpommern,"Kommune, Öffentliche Einrichtung, Verband/Vere...",
1708,80466ba8308f5e3aaa7f720433c71434,False,2025-10-27 02:02:12.484091,https://www.foerderdatenbank.de/FDB/Content/DE...,Teilhabe zugewanderter Menschen und gesellscha...,### Kurztext\n\nWenn Sie sich für den Zusammen...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie über die Gewähr...,Zuschuss,Gesundheit & Soziales,Niedersachsen,"Kommune, Verband/Vereinigung","Niedersächsisches Ministerium für Soziales, Ar..."
1733,122a5f6220d57c8614c593ea50188d31,False,2025-10-27 02:02:12.484091,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Kleinprojekten,### Kurztext\n\nWenn Sie als Einrichtung in Me...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinie zur Förderung v...,Zuschuss,"Arbeit, Aus- & Weiterbildung, Gesundheit & Soz...",Mecklenburg-Vorpommern,"Bildungseinrichtung, Öffentliche Einrichtung, ...",None
2265,df5b03590436483f508055f778ce6f14,False,2025-10-29 02:02:24.873869,https://www.foerderdatenbank.de/FDB/Content/DE...,Maßnahmen der politischen Bildung,### Kurztext\n\nWenn Sie als Bildungsträger Pr...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\n**Richtlinien über die Gewäh...,Zuschuss,"Kultur, Medien & Sport",Sachsen-Anhalt,"Verband/Vereinigung, Öffentliche Einrichtung, ...",Ministerium für Bildung des Landes Sachsen-Anhalt
2396,f18cfe1fafb52b96f83593e58e50eb8d,False,2025-09-29 02:02:18.346459,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Projekten der schulischen übergr...,### Kurztext\n\nWenn Sie Bildungsmaßnahmen zu ...,### rechtliche Voraussetzungen\n\nAntragsberec...,### Richtlinie\n\nRichtlinie des Ministeriums ...,Zuschuss,"Kultur, Medien & Sport",Brandenburg,"Bildungseinrichtung, Verband/Vereinigung","Ministerium für Bildung, Jugend und Sport des ..."

In [10]:
# # Open fund websites for exemplary funds
# for url in df_min_demo['url'].head(10):
#     webbrowser.open(url)

## Which locations are how often funded?

In [11]:
funding_locations = df_min["funding_location"].value_counts()
funding_locations

funding_location
bundesweit                                             581
Nordrhein-Westfalen                                    182
Sachsen                                                181
Bayern                                                 164
Schleswig-Holstein                                     162
Niedersachsen                                          150
Hessen                                                 138
Baden-Württemberg                                      133
Sachsen-Anhalt                                         127
Thüringen                                              117
Hamburg                                                 99
Rheinland-Pfalz                                         94
Mecklenburg-Vorpommern                                  90
Berlin                                                  87
Saarland                                                85
Brandenburg                                             78
Bremen                                                  40
Brandenburg, Berlin                                      9
Berlin, Brandenburg                                      4
Niedersachsen, Bremen, Hamburg                           4
Bremen, Niedersachsen                                    4
bundesweit, Sonstige                                     3
Niedersachsen, Bremen                                    2
Niedersachsen, Hamburg                                   2
Nordrhein-Westfalen, Niedersachsen                       1
Thüringen, Sachsen, Sachsen-Anhalt                       1
Brandenburg, Nordrhein-Westfalen, Sachsen-Anhalt         1
Baden-Württemberg, bundesweit                            1
bundesweit, Brandenburg, Sachsen                         1
Sonstige                                                 1
Brandenburg, Mecklenburg-Vorpommern, Sachsen-Anhalt      1
Mecklenburg-Vorpommern, Hamburg                          1
Hamburg, Schleswig-Holstein                              1
Sonstige, bundesweit                                     1
Berlin, bundesweit                                       1
Name: count, dtype: int64

note: there are very few programs which fund multiple locations

-> wide format may be necessary

## Which funding types are given how often?

In [12]:
funding_types = df_min["funding_type"].value_counts()
funding_types

funding_type
Zuschuss                           1958
Darlehen                            262
Beteiligung                          78
Bürgschaft                           77
Darlehen, Zuschuss                   64
Zuschuss, Darlehen                   37
Garantie                             24
Sonstige                             13
Beteiligung, Darlehen                 7
Darlehen, Bürgschaft                  4
Bürgschaft, Zuschuss                  4
Bürgschaft, Darlehen                  3
Zuschuss, Beteiligung                 3
Beteiligung, Bürgschaft               2
Zuschuss, Bürgschaft                  2
Bürgschaft, Garantie                  1
Beteiligung, Darlehen, Garantie       1
Bürgschaft, Darlehen, Garantie        1
Zuschuss, Sonstige                    1
Bürgschaft, Beteiligung               1
Beteiligung, Zuschuss                 1
Beteiligung, Sonstige                 1
Name: count, dtype: int64

In [ ]:
df_min["funding_type"].value_counts().index[0]

0

In [13]:
funding_types_set = {i.strip() for x in list(df_min["funding_type"].dropna().unique()) for i in x.split(',')}
funding_types_set

{'Beteiligung', 'Bürgschaft', 'Darlehen', 'Garantie', 'Sonstige', 'Zuschuss'}

note: there are very few programms which support different types

-> wide format may be necessary

In [14]:
# bundesland_abbr = {
#     "Bayern": "BY",
#     "Baden-Württemberg": "BW",
#     "Berlin": "BE",
#     "Brandenburg": "BB",
#     "Bremen": "HB",
#     "Hamburg": "HH",
#     "Hessen": "HE",
#     "Mecklenburg-Vorpommern": "MV",
#     "Niedersachsen": "NI",
#     "Nordrhein-Westfalen": "NW",
#     "Rheinland-Pfalz": "RP",
#     "Saarland": "SL",
#     "Sachsen": "SN",
#     "Sachsen-Anhalt": "ST",
#     "Schleswig-Holstein": "SH",
#     "Thüringen": "TH"
# }

bundesland_abbr = config["bundesland_abbr"]

In [15]:
df_min = df_min.drop(columns=["deleted", "on_website_from", "description", "more_info", "legal_basis"])
df_min

,id_hash,url,title,funding_type,funding_area,funding_location,eligible_applicants,funding_body
0,8997afac2cd4a1c4a032f5a5589e381e,https://www.foerderdatenbank.de/FDB/Content/DE...,Aktionsprogramm „Hilfen in Wohnungsnotfällen“,Zuschuss,Gesundheit & Soziales,Nordrhein-Westfalen,"Kommune, Verband/Vereinigung","Ministerium für Arbeit, Gesundheit und Soziale..."
1,b5d0bc46cd945fbba2132d73dfe33c98,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Projekten zum Thema „Zukunftstec...,Zuschuss,Forschung & Innovation (themenspezifisch),bundesweit,"Forschungseinrichtung, Hochschule, Unternehmen...","Bundesministerium für Forschung, Technologie u..."
2,8be11300265934d4afcb8680f1ac2eff,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Maßnahmen des Natürlichen Klimas...,"Darlehen, Zuschuss",Umwelt- & Naturschutz,bundesweit,Unternehmen,"Bundesministerium für Umwelt, Klimaschutz, Nat..."
3,29b4379eb1004eca5fa67b2b053da017,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Forschungsvorhaben von Hochschul...,Zuschuss,Forschung & Innovation (themenoffen),bundesweit,Hochschule,"Bundesministerium für Forschung, Technologie u..."
4,d6482c35f239991eb467b7fba412b2b8,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung von Projekten kommunaler und sonstig...,Zuschuss,"Kultur, Medien & Sport",Rheinland-Pfalz,"Kommune, Verband/Vereinigung",
...,...,...,...,...,...,...,...,...
2567,58c44f8d4e0a3a5a187fb46bba2bee5c,https://www.foerderdatenbank.de/FDB/Content/DE...,Dekarbonisierungsbonus Thüringen,Zuschuss,Energieeffizienz & Erneuerbare Energien,Thüringen,Unternehmen,"Thüringer Ministerium für Wirtschaft, Wissensc..."
2568,5c510714a36b1d412c2dbcae140b0210,https://www.foerderdatenbank.de/FDB/Content/DE...,Förderung der Flurbereinigung (FlurbFördRichtl...,Zuschuss,Landwirtschaft & Ländliche Entwicklung,Brandenburg,"Unternehmen, Privatperson, Verband/Vereinigung","Ministerium für Landwirtschaft, Umwelt und Kli..."
2569,d1045324bdb05fb1150c99f5a4cee386,https://www.foerderdatenbank.de/FDB/Content/DE...,Wohnraumförderungsprogramm – Sonderprogramm zu...,Darlehen,Wohnungsbau & Modernisierung,Saarland,"Privatperson, Unternehmen, Verband/Vereinigung","Ministerium für Inneres, Bauen und Sport"
2570,472c86ae2d94c7452a356f3b98ea3c94,https://www.foerderdatenbank.de/FDB/Content/DE...,Wohnraumförderung – Modernisierung von Mietwoh...,"Darlehen, Zuschuss",Wohnungsbau & Modernisierung,Niedersachsen,"Privatperson, Öffentliche Einrichtung, Kommune...","Niedersächsisches Ministerium für Wirtschaft, ..."
2571,bbe924581ed4c29e79e731884aedf0c4,https://www.foerderdatenbank.de/FDB/Content/DE...,Schaffung von barrierefreiem Mietwohnraum,Zuschuss,Wohnungsbau & Modernisierung,Saarland,"Kommune, Öffentliche Einrichtung, Privatperson...","Ministerium für Inneres, Bauen und Sport"

In [16]:
df_min.to_parquet("../data/sample_dashboard_data.parquet")